### ISSUE TITLE
RFC: support setting run location from CLI and CLI config

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#352]
As a user, I want to determine against which run location / region my checks are executed when using `npx checkly test` so I can choose the region that best reflects my user base or performance characteristics.

# Proposal

* [x] Introduce the `--run-location <location>` CLI flag. The `<location>` is the short code e.g. `eu-west-1` not the friendly name "Ireland". Adding this flag forces all runs to take place from that location.

* [ ] Introduce the `runLocation` default in the `cli` section of `checkly.config.js` so people can determine a default to always use. This setting will be overridden when users also specify the flag, e.g. the flag takes precedence.

**Comment by clample** [comment]
We currently have `--location` and `--private-location` flags for `checkly test`. Having separate flags is useful for the implementation since the backend needs to distinguish between public and private locations.

For `checkly.config.js`, I propose that we accept a `runLocation` or `runPrivateLocation` field. If both are set, we could either give preference to one field or throw an error. I think that throwing an error works better.
