### ISSUE TITLE
`test` command filter does not respect dependency resolution

### ISSUE THREAD

**Issue by kiroushi** [checkly/checkly-cli#441]
There might be the case that passing a path filter to the CLI:

```
npx checkly test path/to/my/file.ts
```

Would end up breaking because the filtering happens after the dependency graph has been fully resolved, which might lead to unfinished/draft files affecting unnecessarily the execution of others.

This is replicable by creating two checks, one with wrong imports, and trying to run the one with correct imports alone.

**Comment by tnolet** [comment]
@kiroushi yes, we need to move the filtering to the project resolving stage, not post resolving.

**Comment by umutuzgur** [comment]
@tnolet why did we go with regex for files matching when we have glob everywhere else?

**Comment by tnolet** [comment]
@umutuzgur because regex is more well known I guess. And playwright/test also uses regex. I'm not married to it. We could do glob for consistency

**Comment by clample** [comment]
I think that there's a related edge case. It's pretty specific, so maybe we just decide that we don't care about it. I thought I'd describe it here, though.

Consider a browser check that's created in a `.check.js` file - `home.check.js`:
```
new BrowserCheck('404-browser-check-1', {
  name: '404 page',
  code: {
    entrypoint: path.join(__dirname, '404.spec.js')
  },
})
```

If the user runs `npx checkly test 404.spec.js`, we currently end up picking the check from the `.check.js` file:
```
$ npx checkly test src/__checks__/404.spec.js

Running 1 checks in eu-west-1.

src/__checks__/home.check.js
  ✔ 404 page (7s)

1 passed, 1 total
```

If we stop parsing all `.check.js` files, then it will be necessary to make a subtle change in the behavior. Rather than picking up the check from the `.check.js` file, we would only load `404.spec.js` and treat the check as an automatically created Browser Check. If there are any environment variables defined in the corresponding `.check.js` file, these wouldn't be applied to the `npx checkly test 404.spec.js` execution. Maybe this will cause some subtle issues.

I don't see a way to keep the current behavior (loading the check from the `.check.js` file) without loading all `.check.js` files.

**Comment by tnolet** [comment]
@clample why do we run the `.check.js` version when the user suppliers a `.spec.js` filter?

**Comment by clample** [comment]
@tnolet 

The project parsing works like: 
Step 1. Load all `.check.js` files 
Step 2. Create Browser Checks for `.spec.js` files that don't have a check from step 1 already. 

This let's us avoid making duplicate checks when loading the `.spec.js` files. 

In a project setup like 
home.check.js
```
new BrowserCheck('404-browser-check-1', {
  name: '404 page',
  code: {
    entrypoint: path.join(__dirname, '404.spec.js')
  },
})
```

404.spec.js
```
console.log('Running check')
```

The CLI will only create the `404 page` check from `home.check.js`. It won't create another check for `404.spec.js`. For `checkly deploy` and `checkly test`, there currently isn't any `.spec.js` version of the check.

When a user runs `npx checkly test 404.spec.js`, the `404 page` check will run since it matches based on the `check.scriptPath`
https://github.com/checkly/checkly-cli/blob/e3e5c7a4ad1edea2720bc41108665c3583dc6ece/package/src/commands/test.ts#L109

**Comment by clample** [comment]
^ this is just describing the way things currently work. Maybe there's a better approach than how things are now, though. I think that this current setup is nice, though.

**Comment by tnolet** [comment]
@clample @kiroushi we looked carefully on how/if we can make this behaviour easy to reason about and reliable.
However, filtering before rendering the project comes with many corner cases, specifically around groups, browser checks and when browser checks are included using glob patterns. In short, to get a predictable, consistent output at runtime we have to render the project.

Therefore we decide not to change this behaviour: when running `test` command with a file name pattern, the whole project cannot have any syntax errors.
