### ISSUE TITLE
bug: running `test` with a filter for a file that is added to a group, it runs duplicate checks

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#509]
### Node.js version

18.12.1

### NPM version

8.19.2

### @checkly/cli version

0.3.14

### Steps to reproduce

Here is a link to a setup that reproduces this. Run `npx checkly test one.spec.ts` and it will run that file, but also double it as it's created via glob in the group, and via an explicit `BrowserCheck` construct.

[https://codesandbox.io/p/sandbox/strange-bhabha-2gltvq?selection=%5B%7B%22endColumn%[…]A7%2C%22startColumn%22%3A19%2C%22startLineNumber%22%3A7%7D%5D](https://codesandbox.io/p/sandbox/strange-bhabha-2gltvq?selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A19%2C%22startLineNumber%22%3A7%7D%5D)

### What is expected?

I expected only the file to run I specifically indicate.

### What is actually happening?

It runs the same check, but in two "instances"

### Any additional comments?

This was reported by a customer

**Comment by clample** [comment]
I'm wondering what the expected behavior should be. Since both checks are associated with `one.spec.ts`, does it make more sense to run the version created directly by `BrowserCheck` or the version created from `CheckGroup`? It seems challenging to pick which one should have priority.

It's worth mentioning that the two versions of the check aren't necessarily the same. The `CheckGroup` and `BrowserCheck` constructs might define `environmentVariables` that configure the behavior of the check (for example, the URL or credentials that are used). In this case, I think that there's a valid use case where users would want to run all of the checks that are associated with `one.spec.ts`.

**Comment by nahuelon** [comment]
@clample , I agree. It seems the current filtering is working OK, picking all checks related with the file. IMHO, the `--grep` should be used to pick just only the spec.file check.

**Comment by nahuelon** [comment]
Decided to keep the current filtering behavior.
