### ISSUE TITLE
feat: Bump nodejs version in checkly-agent

### ISSUE THREAD

**Issue by Stono** [checkly/checkly-cli#981]
### What problem does this feature solve?

Hi, 
Please can we bump the nodejs version in checkly-agent docker image?  It's on 18 which is EOL next april.

For context; we add some additional support scripts to the docker image to help us with deploying checks.  It'd be nice to be able to use things like `import.meta` which is not available on 18.

### How would you implement this feature?

Upgrade node :D

**Comment by sorccu** [comment]
Unfortunately I have been informed that this is not feasible until we release a runtime that supports Node 20. Once we do, then the agent will get updated too. Sadly, we are not able to provide any ETA for this. From what I understand it will not happen soon.

I understand that you had no other repository to report this issue to but since this is not related to the CLI I will have to close it. The correct place to report this to would be https://feedback.checklyhq.com/?sortBy=date%3Adesc.
